public class Barry {


    // create main method 

    public static void main (String [] args) {
    
        // Print introduction to cosole

        displayTitle();
        displayDescription();
    }

    // Create method to display title 
    public static void displayTitle() {
        // print titlr 
        System.out.println("\n\n\t *** Barry's Day Out ***\n\n");
    } 

    public static void displayDescription() {
        // print titlr 
        System.out.println("\n\n\t *** It's a...pleasant day in Dreamera, cloudy as always, people are lively, and you are as...manageable as you usually are, when reaching for your box of smokes, you find only one left! ***\n\n");
        System.out.println("\n\n\t *** Looks like you're gonna have to go and get more...what're you gonna do about it? ***\n\n");
    }

}