public class Barry {


    // create main method 

    public static void main (String [] args) {
        // Print introduction to cosole
    }

    // Create method to display title 
    public static void displayTitle() {
        // print titlr 
        System.out.println("\n\n\t *** Barry's Day Out ***\n\n");
    } 

    public static void displayStart() {
        // print titlr 
        System.out.println("\n\n\t *** It's a...pleasant day in Dreamera ***\n\n");
    }

}